
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    String strSQL = "Select * From Membership_board";
    String strBoardSQL = "Select * From Board";
    String strSaveSQL = "Select * From Saveboard";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        /*try{
        DBM.dbOpen();
        //getDBData(makeSQLWhereBoard(strBoardSQL));
        getDBData(strBoardSQL);
        DBM.dbClose();
        }catch(Exception e){
        System.out.println("SQL Exception : "+e.getMessage());
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        join = new javax.swing.JDialog();
        txt_name = new javax.swing.JTextField();
        btn_idcheck = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_member = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        lbl_pwcheck = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_join = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txt_pw = new javax.swing.JPasswordField();
        txt_pwcheck = new javax.swing.JPasswordField();
        txt_email = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();
        board_list = new javax.swing.JDialog();
        btn_logout = new javax.swing.JButton();
        btn_movetoboard = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_boardsearch = new javax.swing.JButton();
        txt_boardsearch = new javax.swing.JTextField();
        btn_show = new javax.swing.JButton();
        btn_boardsearchtitle = new javax.swing.JButton();
        btn_logoutexit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        board = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtboard_contents = new javax.swing.JTextArea();
        txtboard_title = new javax.swing.JTextField();
        lblboard_title = new javax.swing.JLabel();
        btn_boarddispose = new javax.swing.JButton();
        lblboard_contents1 = new javax.swing.JLabel();
        btn_boardupload = new javax.swing.JButton();
        btn_boardsave = new javax.swing.JButton();
        btn_loadboardsave = new javax.swing.JButton();
        btn_saveupdate = new javax.swing.JButton();
        btn_savedelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_titlereset = new javax.swing.JButton();
        btn_contentsreset = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lbl_loginid = new javax.swing.JLabel();
        lbl_loginpw = new javax.swing.JLabel();
        login_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        login_pw = new javax.swing.JPasswordField();
        btn_loginreset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        join.setModal(true);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        btn_idcheck.setText("중복 확인");
        btn_idcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idcheckActionPerformed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(0, 51, 225));
        lbl_title.setText("회원가입");

        lbl_id.setText("아이디");

        lbl_member.setText("이메일");

        lbl_pw.setText("비밀번호");

        lbl_pwcheck.setText("비밀번호 확인");

        lbl_name.setText("성명");

        btn_join.setText("회원 가입");
        btn_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinActionPerformed(evt);
            }
        });

        btnExit.setText("종료(Exit)");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinLayout = new javax.swing.GroupLayout(join.getContentPane());
        join.getContentPane().setLayout(joinLayout);
        joinLayout.setHorizontalGroup(
            joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinLayout.createSequentialGroup()
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(joinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, joinLayout.createSequentialGroup()
                                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_pwcheck)
                                    .addComponent(lbl_pw)
                                    .addComponent(lbl_id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txt_pw, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_pwcheck)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, joinLayout.createSequentialGroup()
                                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_name)
                                    .addComponent(lbl_member))
                                .addGap(46, 46, 46)
                                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name)
                                    .addComponent(txt_email))))
                        .addGap(18, 18, 18)
                        .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_join, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_idcheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(joinLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lbl_title)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        joinLayout.setVerticalGroup(
            joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_idcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pw)
                    .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pwcheck)
                    .addComponent(txt_pwcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_member)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_join)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        btn_logout.setBackground(new java.awt.Color(227, 240, 247));
        btn_logout.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_logout.setText("로그아웃");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_movetoboard.setBackground(new java.awt.Color(227, 240, 247));
        btn_movetoboard.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_movetoboard.setText("글쓰기");
        btn_movetoboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movetoboardActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btn_boardsearch.setBackground(new java.awt.Color(227, 240, 247));
        btn_boardsearch.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_boardsearch.setText("글쓴이 검색");
        btn_boardsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boardsearchActionPerformed(evt);
            }
        });

        btn_show.setBackground(new java.awt.Color(227, 240, 247));
        btn_show.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_show.setText("내 글 보기");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });

        btn_boardsearchtitle.setBackground(new java.awt.Color(227, 240, 247));
        btn_boardsearchtitle.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_boardsearchtitle.setText("제목 검색");
        btn_boardsearchtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boardsearchtitleActionPerformed(evt);
            }
        });

        btn_logoutexit.setBackground(new java.awt.Color(227, 240, 247));
        btn_logoutexit.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_logoutexit.setText("로그아웃 및 프로그램 종료");
        btn_logoutexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutexitActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(199, 220, 238));

        jPanel8.setBackground(new java.awt.Color(199, 220, 238));
        jPanel8.setPreferredSize(new java.awt.Dimension(722, 51));

        jLabel9.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("게시판");

        jLabel11.setFont(new java.awt.Font("바탕", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("•");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout board_listLayout = new javax.swing.GroupLayout(board_list.getContentPane());
        board_list.getContentPane().setLayout(board_listLayout);
        board_listLayout.setHorizontalGroup(
            board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, board_listLayout.createSequentialGroup()
                .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(board_listLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_logoutexit))
                    .addGroup(board_listLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(txt_boardsearch))
                        .addGap(18, 18, 18)
                        .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_boardsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_show)
                            .addComponent(btn_boardsearchtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_movetoboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(board_listLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        board_listLayout.setVerticalGroup(
            board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_listLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_boardsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_boardsearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(board_listLayout.createSequentialGroup()
                        .addComponent(btn_boardsearchtitle)
                        .addGap(31, 31, 31)
                        .addComponent(btn_show)
                        .addGap(46, 46, 46)
                        .addComponent(btn_movetoboard)
                        .addGap(234, 234, 234))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(board_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout)
                    .addComponent(btn_logoutexit))
                .addGap(40, 40, 40))
        );

        board.setModal(true);

        txtboard_contents.setColumns(20);
        txtboard_contents.setRows(5);
        jScrollPane2.setViewportView(txtboard_contents);

        lblboard_title.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 0, 15)); // NOI18N
        lblboard_title.setForeground(new java.awt.Color(0, 51, 153));
        lblboard_title.setText("제목");

        btn_boarddispose.setBackground(new java.awt.Color(227, 240, 247));
        btn_boarddispose.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_boarddispose.setText("닫기");
        btn_boarddispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boarddisposeActionPerformed(evt);
            }
        });

        lblboard_contents1.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 15)); // NOI18N
        lblboard_contents1.setForeground(new java.awt.Color(0, 51, 153));
        lblboard_contents1.setText("내용");

        btn_boardupload.setBackground(new java.awt.Color(227, 240, 247));
        btn_boardupload.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_boardupload.setText("업로드");
        btn_boardupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boarduploadActionPerformed(evt);
            }
        });

        btn_boardsave.setBackground(new java.awt.Color(227, 240, 247));
        btn_boardsave.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_boardsave.setText("임시 저장");
        btn_boardsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boardsaveActionPerformed(evt);
            }
        });

        btn_loadboardsave.setBackground(new java.awt.Color(227, 240, 247));
        btn_loadboardsave.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_loadboardsave.setText("임시저장 글 불러오기");
        btn_loadboardsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadboardsaveActionPerformed(evt);
            }
        });

        btn_saveupdate.setBackground(new java.awt.Color(227, 240, 247));
        btn_saveupdate.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_saveupdate.setText("임시저장 글 수정");
        btn_saveupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveupdateActionPerformed(evt);
            }
        });

        btn_savedelete.setBackground(new java.awt.Color(227, 240, 247));
        btn_savedelete.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_savedelete.setText("임시저장 글 삭제");
        btn_savedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savedeleteActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(199, 220, 238));

        jLabel8.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("식단 / 운동 적기");

        jLabel10.setFont(new java.awt.Font("바탕", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("•");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_titlereset.setBackground(new java.awt.Color(228, 241, 248));
        btn_titlereset.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_titlereset.setText("제목 지우기");
        btn_titlereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_titleresetActionPerformed(evt);
            }
        });

        btn_contentsreset.setBackground(new java.awt.Color(227, 240, 247));
        btn_contentsreset.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_contentsreset.setText("내용 지우기");
        btn_contentsreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contentsresetActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(227, 240, 247));
        btn_reset.setFont(new java.awt.Font("한컴 말랑말랑 Regular", 0, 15)); // NOI18N
        btn_reset.setText("초기화");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board.getContentPane());
        board.getContentPane().setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(boardLayout.createSequentialGroup()
                                .addComponent(lblboard_title)
                                .addGap(18, 18, 18)
                                .addComponent(txtboard_title, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(boardLayout.createSequentialGroup()
                                .addComponent(lblboard_contents1)
                                .addGap(18, 18, 18)
                                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_loadboardsave, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_savedelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_saveupdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_titlereset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_contentsreset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_boardsave)))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(btn_boardupload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_boarddispose)))
                .addGap(47, 47, 47))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtboard_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblboard_title)
                    .addComponent(btn_titlereset))
                .addGap(18, 18, 18)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(btn_contentsreset)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_boardsave))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblboard_contents1))
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_boardupload)
                            .addComponent(btn_boarddispose)))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_loadboardsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_saveupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_savedelete)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sgin up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_loginid.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbl_loginid.setForeground(new java.awt.Color(0, 0, 255));
        lbl_loginid.setText("ID");

        lbl_loginpw.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbl_loginpw.setForeground(new java.awt.Color(0, 0, 255));
        lbl_loginpw.setText("Password");

        login_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_idActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 41)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Go On a Diet");

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        login_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_pwActionPerformed(evt);
            }
        });

        btn_loginreset.setText("reset");
        btn_loginreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginresetActionPerformed(evt);
            }
        });

        jLabel3.setText("Don't have an account yet?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(143, 204, 238));

        jPanel5.setBackground(new java.awt.Color(226, 240, 248));

        jLabel4.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("GOD");

        jLabel5.setFont(new java.awt.Font("한컴 말랑말랑 Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Welcome Back!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(226, 234, 245));
        jLabel7.setFont(new java.awt.Font("나눔고딕 ExtraBold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 237, 243));
        jLabel7.setText("...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_loginreset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_loginid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_loginpw, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_id, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_pw, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                                .addGap(73, 73, 73))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(445, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1)
                    .addGap(107, 107, 107)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(lbl_loginid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_loginpw)
                .addGap(1, 1, 1)
                .addComponent(login_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_loginreset)
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addGap(147, 147, 147))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(464, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1))
                    .addGap(46, 46, 46)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_idcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idcheckActionPerformed
        strSQL = "SELECT * FROM Membership_board ";
        strSQL = makeSQLWhere(strSQL);

        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                if(txt_id.getText().equals(DBM.DB_rs.getString("Id")))
                {
                    JOptionPane.showMessageDialog(this, "사용할 수 없는 아이디입니다.");
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(this, "사용 가능한 아이디입니다.");
                    return;
                }}
                DBM.DB_rs.close();
                DBM.dbClose();
            }
            catch(Exception e){
                System.out.println("SQLException : "+e.getMessage());}
    }//GEN-LAST:event_btn_idcheckActionPerformed

    private void btn_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinActionPerformed
        strSQL ="INSERT INTO Membership_board VALUES (";

        if(txt_id.getText()==""){
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요.");
            return;
        }
        else
        strSQL += "'"+txt_id.getText()+"', ";

        if(txt_pw.getText().equals(txt_pwcheck.getText())){
            strSQL += "'"+txt_pw.getText()+"', ";
        }
        else
        {JOptionPane.showMessageDialog(this, "비밀번호가 동일하지 않습니다.");
            return;}

        strSQL += "'"+txt_name.getText()+"', ";
        strSQL += "'"+txt_email.getText()+"')";

        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            strSQL = "Select * From Membership_board";
            // getDBData(strSQL);
            DBM.dbClose();
        }
        catch(Exception e){
            System.out.println("SQLException : " +e.getMessage());}
    }//GEN-LAST:event_btn_joinActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        txt_id.setText(null);
        txt_pw.setText(null);
        txt_pwcheck.setText(null);
        txt_name.setText(null);
        txt_email.setText(null);
        join.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_boarddisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boarddisposeActionPerformed
        board.dispose();
    }//GEN-LAST:event_btn_boarddisposeActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        login_id.setText(null);
        login_pw.setText(null);
        board_list.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_movetoboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movetoboardActionPerformed
        board.setLocation(420, 200);
        board.setSize(800, 800);
        board.show();
    }//GEN-LAST:event_btn_movetoboardActionPerformed

    private void btn_boarduploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boarduploadActionPerformed
        strBoardSQL = "INSERT INTO Board VALUES(";
        strBoardSQL += "'" +txtboard_title.getText()+"', ";
        strBoardSQL += "'"+ login_id.getText() +"', ";
        strBoardSQL += "'" +txtboard_contents.getText()+"') ";
        
        try{
        DBM.dbOpen();
        DBM.DB_stmt.executeUpdate(strBoardSQL);
        strBoardSQL = "Select * From Board";
        //getDBData(strBoardSQL);
        DBM.dbClose();
        System.out.println("업로드 성공!");
        txtboard_title.setText(null);
        txtboard_contents.setText(null);
        }catch(Exception e){
        System.out.println("SQL Exception : "+e.getMessage());
        }
    }//GEN-LAST:event_btn_boarduploadActionPerformed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        strBoardSQL = "SELECT * From Board ";
        strBoardSQL = makeSQLWhereBoardid(strBoardSQL);

        String strOutput = "제 목\t글쓴이\t내 용\n";
        
        jTextArea1.setText(strOutput);
        try{
        DBM.dbOpen();
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strBoardSQL);
        while(DBM.DB_rs.next()){
        strOutput = "";
        strOutput += DBM.DB_rs.getString("Title")+"\t";
        strOutput += DBM.DB_rs.getString("Writer")+"\t";
        strOutput += DBM.DB_rs.getString("Contents")+"\n";
        jTextArea1.append(strOutput);
        }
        DBM.DB_rs.close();
        }
        catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());}
        
        
       
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_boardsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boardsearchActionPerformed
        strBoardSQL = "SELECT * From Board ";
        strBoardSQL = makeSQLWhereBoardwriter(strBoardSQL);

        String strOutput = "제 목\t글쓴이\t내 용\n";
        
        jTextArea1.setText(strOutput);
        try{
        DBM.dbOpen();
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strBoardSQL);
        while(DBM.DB_rs.next()){
        strOutput = "";
        strOutput += DBM.DB_rs.getString("Title")+"\t";
        strOutput += DBM.DB_rs.getString("Writer")+"\t";
        strOutput += DBM.DB_rs.getString("Contents")+"\n";
        jTextArea1.append(strOutput);
        }
        DBM.DB_rs.close();
        }
        catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());}
    }//GEN-LAST:event_btn_boardsearchActionPerformed

    private void btn_boardsearchtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boardsearchtitleActionPerformed
        strBoardSQL = "SELECT * From Board ";
        strBoardSQL = makeSQLWhereBoardtitle(strBoardSQL);

        String strOutput = "제 목\t글쓴이\t내 용\n";
        
        jTextArea1.setText(strOutput);
        try{
        DBM.dbOpen();
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strBoardSQL);
        while(DBM.DB_rs.next()){
        strOutput = "";
        strOutput += DBM.DB_rs.getString("Title")+"\t";
        strOutput += DBM.DB_rs.getString("Writer")+"\t";
        strOutput += DBM.DB_rs.getString("Contents")+"\n";
        jTextArea1.append(strOutput);
        }
        DBM.DB_rs.close();
        }
        catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());}
    }//GEN-LAST:event_btn_boardsearchtitleActionPerformed

    private void btn_logoutexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutexitActionPerformed
        login_id.setText(null);
        login_pw.setText(null);
        System.exit(0);
    }//GEN-LAST:event_btn_logoutexitActionPerformed

    private void btn_boardsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boardsaveActionPerformed
    strSaveSQL = "Insert INTO Saveboard VALUES( ";
    strSaveSQL += "'" +txtboard_title.getText()+"', ";
    strSaveSQL += "'"+ login_id.getText() +"', ";
    strSaveSQL += "'" +txtboard_contents.getText()+"') ";
        
        try{
        DBM.dbOpen();     
        DBM.DB_stmt.executeUpdate(strSaveSQL);
        strSaveSQL = "Select * From Saveboard";
        DBM.dbClose();
        System.out.println("임시 저장 완료");
        }catch(Exception e){
        System.out.println("SQL Exception : "+e.getMessage());
        }
    }//GEN-LAST:event_btn_boardsaveActionPerformed

    private void btn_loadboardsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadboardsaveActionPerformed
        strSaveSQL = "Select * From Saveboard ";
        strSaveSQL = makeSQLWhereSaveBoard(strSaveSQL);
        
        try{
        DBM.dbOpen();
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strSaveSQL);
        while(DBM.DB_rs.next()){
        txtboard_title.setText(DBM.DB_rs.getString("Title"));
        txtboard_contents.setText(DBM.DB_rs.getString("Contents"));
        }
        DBM.DB_rs.close();
        DBM.dbClose();
        }
        catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());
        }
    }//GEN-LAST:event_btn_loadboardsaveActionPerformed

    private void btn_saveupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveupdateActionPerformed
        strSaveSQL = "UPDATE Saveboard SET ";
    strSaveSQL += "Title = "+ "'" +txtboard_title.getText()+"', ";
    strSaveSQL += "Writer = "+ "'"+ login_id.getText() +"', ";
    strSaveSQL += "Contents = "+ "'" +txtboard_contents.getText()+"' ";
    strSaveSQL = makeSQLWhereSaveBoard(strSaveSQL);
        
        try{
        DBM.dbOpen();     
        DBM.DB_stmt.executeUpdate(strSaveSQL);
        strSaveSQL = "Select * From Saveboard";
        DBM.dbClose();
        System.out.println("임시 저장 글 수정 완료");
        }catch(Exception e){
        System.out.println("SQL Exception : "+e.getMessage());
        }
    }//GEN-LAST:event_btn_saveupdateActionPerformed

    private void btn_savedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savedeleteActionPerformed
    strSaveSQL = "DELETE FROM Saveboard ";
    strSaveSQL = makeSQLWhereSaveBoard(strSaveSQL);
        
        try{
        DBM.dbOpen();     
        DBM.DB_stmt.executeUpdate(strSaveSQL);
        strSaveSQL = "Select * From Saveboard";
        DBM.dbClose();
        System.out.println("임시 저장글 삭제 완료");
        }catch(Exception e){
        System.out.println("SQL Exception : "+e.getMessage());
        }
    }//GEN-LAST:event_btn_savedeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        join.setLocation(400, 400);
        join.setSize(400, 400);
        join.show();
        //lbl_userid.setText(login_id.getText()+"님, 반갑습니다.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String inputid = login_id.getText();
        String inputpw = login_pw.getText();

        String strSQL = "SELECT * FROM Membership_board ";
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                String uid=DBM.DB_rs.getString("Id");
                String upw=DBM.DB_rs.getString("Password");
                //                    strSQL += " WHERE Membership.Id = '"+uid+"'";
                //                    return strSQL;
                //                String upw=DBM.DB_rs.getString("Password WHERE Membership.Id = '"+uid+"'");
                //                    String upw = strSQL;
                //                    String upw = "SELECT * FROM Membership Password WHERE Membership.Id='"+inputid+"'";
                if((inputid.equals(uid)) && (inputpw.equals(upw))){
                    board_list.setLocation(400, 300);
                    board_list.setSize(800, 700);
                    board_list.show();}
                else{
                    JOptionPane.showMessageDialog(this, "아이디 또는 비밀번호를 확인하세요");
                    return;
                }
            }
            DBM.DB_rs.close();
            DBM.dbClose();
        }
        catch(Exception e){
            System.out.println("SQLException : "+e.getMessage());}
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginresetActionPerformed
        login_id.setText(null);
        login_pw.setText(null);
    }//GEN-LAST:event_btn_loginresetActionPerformed

    private void login_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_pwActionPerformed
   
    }//GEN-LAST:event_login_pwActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txtboard_title.setText(null);
        txtboard_contents.setText(null);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_contentsresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contentsresetActionPerformed
        txtboard_contents.setText(null);
    }//GEN-LAST:event_btn_contentsresetActionPerformed

    private void btn_titleresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_titleresetActionPerformed
        txtboard_title.setText(null);
    }//GEN-LAST:event_btn_titleresetActionPerformed

    private void login_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    public String makeSQLWhere(String strQuery){
    strQuery += " WHERE Membership_board.Id = '"+txt_id.getText()+"'";
    return strQuery;
    }
    public String makeSQLWhereBoardid(String strBoardQuery){
    strBoardQuery += " WHERE Board.Writer = '"+login_id.getText()+"'";
    return strBoardQuery;
    }
    public String makeSQLWhereBoardtitle(String strBoardQuery){
    strBoardQuery += " WHERE Board.Title = '"+txt_boardsearch.getText()+"'";
    return strBoardQuery;
    }
    public String makeSQLWhereBoardwriter(String strBoardQuery){
    strBoardQuery += " WHERE Board.Writer = '"+txt_boardsearch.getText()+"'";
    return strBoardQuery;
    }
    public String makeSQLWhereSaveBoard(String strSaveboardQuery){
    strSaveboardQuery += " WHERE Saveboard.Writer = '"+login_id.getText()+"'";
    return strSaveboardQuery;
    }

    /*private final void getSaveWriterData(String strSaveboardQuery){
    strSaveSQL = "Select * From Saveboard ";
    strSaveSQL = makeSQLWhereSaveBoard(strSaveSQL);
        
    try{
    DBM.dbOpen();
    DBM.DB_rs = DBM.DB_stmt.executeQuery(strSaveboardQuery);
    while(DBM.DB_rs.next()){
    
    }
    }catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());
    }
    }*/
    
        private final void getDBData(String strBoardQuery) {
        String strOutput = "제 목\t글쓴이\t내 용\n";
        
        jTextArea1.setText(strOutput);
        try{
        DBM.dbOpen();
        DBM.DB_rs = DBM.DB_stmt.executeQuery(strBoardQuery);
        while(DBM.DB_rs.next()){
        strOutput = "";
        strOutput += DBM.DB_rs.getString("Title")+"\t";
        strOutput += DBM.DB_rs.getString("Writer")+"\t";
        strOutput += DBM.DB_rs.getString("Contents")+"\n";
        jTextArea1.append(strOutput);
        }
        DBM.DB_rs.close();
        }
        catch(Exception e){
        System.out.println("SQLException : "+e.getMessage());}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog board;
    private javax.swing.JDialog board_list;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btn_boarddispose;
    private javax.swing.JButton btn_boardsave;
    private javax.swing.JButton btn_boardsearch;
    private javax.swing.JButton btn_boardsearchtitle;
    private javax.swing.JButton btn_boardupload;
    private javax.swing.JButton btn_contentsreset;
    private javax.swing.JButton btn_idcheck;
    private javax.swing.JButton btn_join;
    private javax.swing.JButton btn_loadboardsave;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_loginreset;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_logoutexit;
    private javax.swing.JButton btn_movetoboard;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_savedelete;
    private javax.swing.JButton btn_saveupdate;
    private javax.swing.JButton btn_show;
    private javax.swing.JButton btn_titlereset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog join;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_loginid;
    private javax.swing.JLabel lbl_loginpw;
    private javax.swing.JLabel lbl_member;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JLabel lbl_pwcheck;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lblboard_contents1;
    private javax.swing.JLabel lblboard_title;
    private javax.swing.JTextField login_id;
    private javax.swing.JPasswordField login_pw;
    private javax.swing.JTextField txt_boardsearch;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JPasswordField txt_pwcheck;
    private javax.swing.JTextArea txtboard_contents;
    private javax.swing.JTextField txtboard_title;
    // End of variables declaration//GEN-END:variables
}
